name: NASA project CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js version 16
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: npm install
            - run: npm install --prefix client 
            - run: npm install --prefix server
            - run: npm run build --prefix client
